### ISSUE TITLE
Nerveskey Compatibility

### ISSUE THREAD

**Issue by fire** [nerves-hub/nerves_key#50]
I'm trying the Udoo bolt as a nerves platform.

Thoughts on 
[iot-hsm.pdf](https://github.com/nerves-hub/nerves_key/files/4842512/iot-hsm.pdf) being compatible with this code.

The UDOO bolt has a grove connector and it's possible to go from grove to qwiic.

**Comment by fhunleth** [comment]
That looks like it should work. The main issue people run into is reducing the I2C bus speed to 100 kHz. It may default to 400 kHz and that's too fast for waking up the ATECC608A. 

p.s. the UDOO Bolt's specs are amazing.
